var properties = [
    {
        imageProperty: 'sea-horse.jpg',
        address: 'Avellaneda 678',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '2',
        bathQuant: '3',
        propType: 'Semipiso',
        description: 'Exclusivo departamento de 3 ambientes con balcón al frente en planta baja de 100m2 - Doble cochera u opcional cochera/ baulera - Diseño minimalista y gran funcionalidad',
    },
    {
        imageProperty: 'P3290001-300x167.jpg',
        address: 'Chubut 400',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '4',
        bathQuant: '2',
        propType: 'Casa',
        description: '5 metros de ancho por 30 mts de fondo , con las comodidades de un lote propio, 4 dormitorios, excelente diseño.',
    },
    {
        imageProperty: 'IMG_20171125_131048623_HDR-300x167.jpg',
        address: 'Villegas 2706',
        location: 'San Justo',
        status: 'Alquiler',
        bedQuant: '1',
        bathQuant: '1',
        propType: 'Departamento',
        description: 'Hermoso departamento de 2 amb. luminoso con vista abierta, living comedor, cocina, baño completo con bañera, dormitorio con placard.',
    },
    {
        imageProperty: 'P1010964-300x167.jpg',
        address: 'Castelli 600',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '2',
        bathQuant: '1',
        propType: 'Casa',
        description: 'Tipo Chalet en 2 plantas, en excelente estado.Aire acondicionado, Alarma, Parrilla, Servicios',
    },
    {
        imageProperty: 'P8020004-300x167.jpg',
        address: 'Pola 1200',
        location: 'Morón',
        status: 'Venta',
        bedQuant: '3',
        bathQuant: '1',
        propType: 'Casa',
        description: 'Hermosa casa desarrollada sobre lote propio de 10x25. PB: Living en desnivel con hogar, Comedor, Cocina-Comedor diario con muebles bajomesada',
    },
    {
        imageProperty: 'DSC_0155-300x167.jpg',
        address: 'Paloma 0',
        location: 'Villa Ventana',
        status: 'Alquiler',
        bedQuant: '5',
        bathQuant: '5',
        propType: 'Quinta',
        description: 'Complejo de cabañas equipadas. Casa principal de 4 amb. Quincho 40 m2 cocina, baño y parrilla. Piscina de 5x8 m.',
    },
    {
        imageProperty: '1563595105-300x167.jpg',
        address: 'Tucuman 2200',
        location: 'Castelar',
        status: 'Venta',
        bedQuant: '2',
        bathQuant: '1',
        propType: 'Casa',
        description: '2 dormitorios y posibilidad de 3º dormitorio y ampliar en planta alta. Muy buen estado. Garage pasante y jardín. Parrilla.',
    },
    {
        imageProperty: 'IMG_20170211_122011927_HDR-300x167.jpg',
        address: 'Espora 100',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '2',
        bathQuant: '1',
        propType: 'Departamento',
        description: 'Departamento 3 ambientes con lavadero y Balcón al frente – Venta Condicionada – APTO CRÉDITO. Calefacción, dos dormitorios.',
    },
    {
        imageProperty: 'maestraLascano300.jpg',
        address: 'Maestra Lascano 300',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '1',
        bathQuant: '1',
        propType: 'Departamento',
        description: 'Hermoso departamento de 2 ambienters con doble balcón al frente y lateral. Cochera cubierta.',
    },
    {
        imageProperty: 'espora44.jpg',
        address: 'Espora 44',
        location: 'Ramos Mejía',
        status: 'Alquiler',
        bedQuant: '3',
        bathQuant: '1',
        propType: 'Departamento',
        description: 'Cómodo departamento al frente de 4 ambientes. Dormitorio principal en suite. Baño con hidromasajes. Escritorio.',
    },
    {
        imageProperty: 'cabral400.jpg',
        address: 'Sgto Cabral 400',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '3',
        bathQuant: '3',
        propType: 'Casa',
        description: 'Excelente casa. Ideal destino vivienda o comercial. Local 25 m2 con baño. Entrada de auto. 3 dormitorios, uno en planta baja. Escritorio. Patio y terraza.',
    },
    {
        imageProperty: 'saavedra3970_ciudadela.jpg',
        address: 'Saavedra 3970',
        location: 'Ciudadela',
        status: 'Venta',
        bedQuant: '1',
        bathQuant: '1',
        propType: 'Departamento',
        description: 'Departamento al contrafrente de 2 ambientes a 3 cuadras de la estación de Ciudadela Norte. Edificio con ascensor.',
    },
    {
        imageProperty: 'alvarado29.jpg',
        address: 'Alvarado 29',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '3',
        bathQuant: '2',
        propType: 'Casa',
        description: 'Amplia y cómoda casa de 4 ambientes. Living comedor con hogar. Comedor, cocina garage baño. Dependencia con baño. 3 dormitorios.',
    },
    {
        imageProperty: 'rosales4300Ciudadela.jpg',
        address: 'Rosales 4300',
        location: 'Ciudadela',
        status: 'Venta',
        bedQuant: '2',
        bathQuant: '1',
        propType: 'Galpón',
        description: 'Amplio galpón. PB. Local al frente con cortina metálica y puerta de acceso lateral independiente con pequeña. 2 oficinas, baño. Patio. Pileta de lavado en el bajo escalera. PA. Amplio ambiente entero, balcón al frente y terraza.',
    },
    {
        imageProperty: '1695054611.jpg',
        address: 'Alberdi 128',
        location: 'Ramos Mejía',
        status: 'Venta',
        bedQuant: '3',
        bathQuant: '2',
        propType: 'Piso',
        description: 'Excelente piso de categoría en el centro de Ramos Mejía. Dormitorio principal en suite con vestidor y dos dormitorios. Balcón al frente. 2 cocheras y 2 bauleras. Edificio con SUM, parrilla y barra, piscina y gym.',
    },
];